name: C/C++ CI

on:
  push:
    branches: [ "main", "nemirko", "divider" ]
  pull_request:
    branches: [ "main", "nemirko", "divider" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installation
      run: sudo apt install -y googletest libgtest-dev build-essential gcovr
    - name: make
      run: make
    - name: execute
      run: ./a.out
